### Joining results from several models

In [12]:
from pathlib import Path
import pandas as pd

In [13]:
base_model = ('persistence', '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/persistence/')
models_to_join = {
    'cnn_23_01' : '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01/'
}

In [14]:
def join_results(metrics_file, metric_columns, index_column):
    def rename_cols(cols, suffix):
        return {col : col+'_'+suffix for col in cols}

    df_groups_joined  = pd.read_csv(
        Path(base_model[1])/metrics_file, index_col=index_column)\
        [metric_columns]\
        .rename(columns=rename_cols(metric_columns, base_model[0]))

    for model in models_to_join:
        df_groups = pd.read_csv(
            Path(models_to_join[model])/metrics_file, index_col=index_column)\
            [metric_columns]\
            .rename(columns=rename_cols(metric_columns, model))

        df_groups_joined = df_groups_joined.join(
            df_groups,
            how='outer'
        )
    return df_groups_joined

df_groups_joined = join_results(metrics_file='groups_metrics.csv', metric_columns=['NRMSE'], index_column='task')
df_groups_joined

          NRMSE_persistence  NRMSE_cnn_23_01
task
group_1                 NaN         0.223995
group_2            0.000023         0.191672
group_3           18.085146              inf
group_4          472.422067              NaN
task_1-1                NaN         0.417712
task_1-2                NaN         0.049526
task_1-3                NaN         0.204539
task_2-1           0.000023         0.379845
task_2-2                NaN         0.057579
task_2-3                NaN         0.145853
task_3-1           0.000817              inf
task_3-2          32.904090         0.612601
task_3-3                NaN              inf
task_4-1          50.617296              NaN
task_4-4           0.000003              NaN
task_4-5       38950.518006              NaN

In [15]:
df_signals_joined = join_results(metrics_file='signals_metrics.csv', metric_columns=['RMSE','NRMSE'], index_column=['task', 'feature_name'])
df_signals_joined

                                                             RMSE_persistence  NRMSE_persistence  RMSE_cnn_23_01  NRMSE_cnn_23_01
task     feature_name
task_1-1 equilibrium-beta_normal                                          NaN                NaN    4.213282e-01         0.519897
         equilibrium-beta_pol                                             NaN                NaN    9.978961e-02         0.566036
         equilibrium-beta_tor                                             NaN                NaN    9.994155e-01         0.501917
         equilibrium-bphi_rmag                                            NaN                NaN    2.751502e-02         0.554561
         equilibrium-bvac_rmag                                            NaN                NaN    2.042257e-02         0.376250
         equilibrium-elongation                                           NaN                NaN    6.739340e-02         0.410682
         equilibrium-elongation_axis                                      NaN                NaN    7.536777e-02         0.495563
         equilibrium-magnetic_axis_r                                      NaN                NaN    2.376732e-02         0.291417
         equilibrium-magnetic_axis_z                                      NaN                NaN    1.046621e-02         0.506165
         equilibrium-minor_radius                                         NaN                NaN    1.749019e-02         0.329033
         equilibrium-q95                                                  NaN                NaN    8.668640e-01         0.321610
         equilibrium-triangularity_lower                                  NaN                NaN    3.193537e-02         0.379936
         equilibrium-triangularity_upper                                  NaN                NaN    3.013362e-02         0.411485
         equilibrium-x_point_r                                            NaN                NaN    6.731983e-02         0.528581
         equilibrium-x_point_z                                            NaN                NaN    8.374822e-02         0.072540
task_1-2 equilibrium-lcfs_r                                               NaN                NaN    2.146051e-02         0.057205
         equilibrium-lcfs_z                                               NaN                NaN    2.695049e-02         0.041846
task_1-3 equilibrium-psi                                                  NaN                NaN    1.081056e-02         0.204539
task_2-1 equilibrium-beta_normal                                          NaN                NaN    4.041106e-01         0.498651
         equilibrium-beta_pol                                             NaN                NaN    9.137102e-02         0.518283
         equilibrium-beta_tor                                             NaN                NaN    9.734545e-01         0.488879
         equilibrium-bphi_rmag                                            NaN                NaN    2.599441e-02         0.523914
         equilibrium-bvac_rmag                                            NaN                NaN    1.947830e-02         0.358854
         equilibrium-elongation                                           NaN                NaN    6.137721e-02         0.374020
         equilibrium-elongation_axis                                      NaN                NaN    6.887451e-02         0.452868
         equilibrium-magnetic_axis_r                                      NaN                NaN    2.119090e-02         0.259827
         equilibrium-magnetic_axis_z                                      NaN                NaN    1.176519e-02         0.568986
         equilibrium-minor_radius                                         NaN                NaN    1.652749e-02         0.310922
         equilibrium-q95                                                  NaN                NaN    7.934883e-01         0.294388
         equilibrium-triangularity_lower                                  NaN                NaN    3.070389e-02         0.365285
         equilibrium-triangularity_upper                                  NaN                NaN    3.058995e-02         0.417717
         equilibrium-x_point_r                                            NaN                NaN    7.825663e-02         0.614454
         equilibrium-x_point_z                                            NaN                NaN    9.151698e-02         0.079269
         pf_active-coil_current                                      0.271530       5.364052e-05    1.621453e+03         0.320316
         pf_active-solenoid_current                                  0.176495       1.416424e-05    2.399108e+03         0.192536
         summary-ip                                                  0.338200       1.182406e-06    5.664411e+04         0.198037
task_2-2 equilibrium-lcfs_r                                               NaN                NaN    2.328889e-02         0.062079
         equilibrium-lcfs_z                                               NaN                NaN    3.418533e-02         0.053080
task_2-3 equilibrium-psi                                                  NaN                NaN    7.708846e-03         0.145853
task_3-1 thomson_scattering-n_e                                      0.447473       3.562563e-20             inf              inf
         thomson_scattering-t_e                                      0.489810       1.633105e-03    1.063728e+02         0.354664
task_3-2 soft_x_rays-horizontal_cam_lower                            0.404062       2.632268e+01    6.658603e-03         0.433775
         soft_x_rays-horizontal_cam_upper                            0.753806       7.161695e+01    7.437990e-03         0.706662
         spectrometer_visible-filter_spectrometer_dalpha...          0.759152       1.960764e+00    2.700000e-01         0.697365
task_3-3 equilibrium-beta_normal                                          NaN                NaN    5.331265e-01         0.657850
         equilibrium-beta_pol                                             NaN                NaN    1.167702e-01         0.662355
         equilibrium-beta_tor                                             NaN                NaN    1.234607e+00         0.620033
         thomson_scattering-n_e                                           NaN                NaN             inf              inf
         thomson_scattering-t_e                                           NaN                NaN    1.490119e+02         0.496830
task_4-1 soft_x_rays-horizontal_cam_lower                            0.531934       3.465285e+01             NaN              NaN
         soft_x_rays-horizontal_cam_upper                            0.916349       8.705969e+01             NaN              NaN
task_4-4 summary-ip                                                  0.760081       2.657374e-06             NaN              NaN
task_4-5 magnetics-b_field_pol_probe_omv_voltage                     1.721265       1.309427e+01             NaN              NaN
         magnetics-b_field_tor_probe_cc_field                        1.766652       1.095489e+05             NaN              NaN

In [7]:
df_signals_joined = join_results(metrics_file='signals_metrics.csv', metric_columns=['RMSE','NRMSE'], index_column=['task', 'feature_name'])
df_signals_joined

                                                             RMSE_persistence  \
task     feature_name
task_1-1 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         equilibrium-bphi_rmag                                            NaN
         equilibrium-bvac_rmag                                            NaN
         equilibrium-elongation                                           NaN
         equilibrium-elongation_axis                                      NaN
         equilibrium-magnetic_axis_r                                      NaN
         equilibrium-magnetic_axis_z                                      NaN
         equilibrium-minor_radius                                         NaN
         equilibrium-q95                                                  NaN
         equilibrium-triangularity_lower                                  NaN
         equilibrium-triangularity_upper                                  NaN
         equilibrium-x_point_r                                            NaN
         equilibrium-x_point_z                                            NaN
task_1-2 equilibrium-lcfs_r                                               NaN
         equilibrium-lcfs_z                                               NaN
task_1-3 equilibrium-psi                                                  NaN
task_2-1 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         equilibrium-bphi_rmag                                            NaN
         equilibrium-bvac_rmag                                            NaN
         equilibrium-elongation                                           NaN
         equilibrium-elongation_axis                                      NaN
         equilibrium-magnetic_axis_r                                      NaN
         equilibrium-magnetic_axis_z                                      NaN
         equilibrium-minor_radius                                         NaN
         equilibrium-q95                                                  NaN
         equilibrium-triangularity_lower                                  NaN
         equilibrium-triangularity_upper                                  NaN
         equilibrium-x_point_r                                            NaN
         equilibrium-x_point_z                                            NaN
         pf_active-coil_current                                      0.160581
         pf_active-solenoid_current                                  0.152229
         summary-ip                                                  0.159397
task_2-2 equilibrium-lcfs_r                                               NaN
         equilibrium-lcfs_z                                               NaN
task_2-3 equilibrium-psi                                                  NaN
task_3-1 thomson_scattering-n_e                                      0.423540
         thomson_scattering-t_e                                      0.442482
task_3-2 soft_x_rays-horizontal_cam_lower                            0.281268
         soft_x_rays-horizontal_cam_upper                            0.562667
         spectrometer_visible-filter_spectrometer_dalpha...          0.502936
task_3-3 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         thomson_scattering-n_e                                           NaN
         thomson_scattering-t_e                                           NaN
task_4-1 soft_x_rays-horizontal_cam_lower                            0.441886
         soft_x_rays-horizontal_cam_upper                            0.793485
task_4-4 summary-ip                                                  0.575937
task_4-5 magnetics-b_field_pol_probe_omv_voltage                     1.365683
         magnetics-b_field_tor_probe_cc_field                        1.256059

                                                             NRMSE_persistence  \
task     feature_name
task_1-1 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         equilibrium-bphi_rmag                                             NaN
         equilibrium-bvac_rmag                                             NaN
         equilibrium-elongation                                            NaN
         equilibrium-elongation_axis                                       NaN
         equilibrium-magnetic_axis_r                                       NaN
         equilibrium-magnetic_axis_z                                       NaN
         equilibrium-minor_radius                                          NaN
         equilibrium-q95                                                   NaN
         equilibrium-triangularity_lower                                   NaN
         equilibrium-triangularity_upper                                   NaN
         equilibrium-x_point_r                                             NaN
         equilibrium-x_point_z                                             NaN
task_1-2 equilibrium-lcfs_r                                                NaN
         equilibrium-lcfs_z                                                NaN
task_1-3 equilibrium-psi                                                   NaN
task_2-1 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         equilibrium-bphi_rmag                                             NaN
         equilibrium-bvac_rmag                                             NaN
         equilibrium-elongation                                            NaN
         equilibrium-elongation_axis                                       NaN
         equilibrium-magnetic_axis_r                                       NaN
         equilibrium-magnetic_axis_z                                       NaN
         equilibrium-minor_radius                                          NaN
         equilibrium-q95                                                   NaN
         equilibrium-triangularity_lower                                   NaN
         equilibrium-triangularity_upper                                   NaN
         equilibrium-x_point_r                                             NaN
         equilibrium-x_point_z                                             NaN
         pf_active-coil_current                                   3.172252e-05
         pf_active-solenoid_current                               1.221689e-05
         summary-ip                                               5.572782e-07
task_2-2 equilibrium-lcfs_r                                                NaN
         equilibrium-lcfs_z                                                NaN
task_2-3 equilibrium-psi                                                   NaN
task_3-1 thomson_scattering-n_e                                   3.372019e-20
         thomson_scattering-t_e                                   1.475307e-03
task_3-2 soft_x_rays-horizontal_cam_lower                         1.832320e+01
         soft_x_rays-horizontal_cam_upper                         5.345743e+01
         spectrometer_visible-filter_spectrometer_dalpha...       1.298999e+00
task_3-3 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         thomson_scattering-n_e                                            NaN
         thomson_scattering-t_e                                            NaN
task_4-1 soft_x_rays-horizontal_cam_lower                         2.878671e+01
         soft_x_rays-horizontal_cam_upper                         7.538676e+01
task_4-4 summary-ip                                               2.013572e-06
task_4-5 magnetics-b_field_pol_probe_omv_voltage                  1.038924e+01
         magnetics-b_field_tor_probe_cc_field                     7.788733e+04

                                                             RMSE_cnn_23_01  \
task     feature_name
task_1-1 equilibrium-beta_normal                               3.083535e-01
         equilibrium-beta_pol                                  7.079668e-02
         equilibrium-beta_tor                                  7.889075e-01
         equilibrium-bphi_rmag                                 2.187909e-02
         equilibrium-bvac_rmag                                 1.825846e-02
         equilibrium-elongation                                5.658072e-02
         equilibrium-elongation_axis                           6.291435e-02
         equilibrium-magnetic_axis_r                           1.991114e-02
         equilibrium-magnetic_axis_z                           8.374295e-03
         equilibrium-minor_radius                              1.461739e-02
         equilibrium-q95                                       6.992082e-01
         equilibrium-triangularity_lower                       2.691892e-02
         equilibrium-triangularity_upper                       2.532577e-02
         equilibrium-x_point_r                                 4.586435e-02
         equilibrium-x_point_z                                 6.164280e-02
task_1-2 equilibrium-lcfs_r                                    1.868824e-02
         equilibrium-lcfs_z                                    2.462266e-02
task_1-3 equilibrium-psi                                       6.364746e-03
task_2-1 equilibrium-beta_normal                               3.312698e-01
         equilibrium-beta_pol                                  7.422029e-02
         equilibrium-beta_tor                                  8.278749e-01
         equilibrium-bphi_rmag                                 2.245707e-02
         equilibrium-bvac_rmag                                 1.818091e-02
         equilibrium-elongation                                5.476007e-02
         equilibrium-elongation_axis                           6.089234e-02
         equilibrium-magnetic_axis_r                           1.884552e-02
         equilibrium-magnetic_axis_z                           1.012266e-02
         equilibrium-minor_radius                              1.465561e-02
         equilibrium-q95                                       6.880221e-01
         equilibrium-triangularity_lower                       2.754508e-02
         equilibrium-triangularity_upper                       2.786351e-02
         equilibrium-x_point_r                                 5.904679e-02
         equilibrium-x_point_z                                 7.363112e-02
         pf_active-coil_current                                1.526914e+03
         pf_active-solenoid_current                            2.158003e+03
         summary-ip                                            5.299098e+04
task_2-2 equilibrium-lcfs_r                                    2.133111e-02
         equilibrium-lcfs_z                                    3.209471e-02
task_2-3 equilibrium-psi                                       5.091208e-03
task_3-1 thomson_scattering-n_e                                         inf
         thomson_scattering-t_e                                1.000844e+02
task_3-2 soft_x_rays-horizontal_cam_lower                      5.377505e-03
         soft_x_rays-horizontal_cam_upper                      6.314699e-03
         spectrometer_visible-filter_spectrometer_dalpha...    2.359782e-01
task_3-3 equilibrium-beta_normal                               4.023889e-01
         equilibrium-beta_pol                                  8.587466e-02
         equilibrium-beta_tor                                  9.732271e-01
         thomson_scattering-n_e                                         inf
         thomson_scattering-t_e                                1.404292e+02
task_4-1 soft_x_rays-horizontal_cam_lower                               NaN
         soft_x_rays-horizontal_cam_upper                               NaN
task_4-4 summary-ip                                                     NaN
task_4-5 magnetics-b_field_pol_probe_omv_voltage                        NaN
         magnetics-b_field_tor_probe_cc_field                           NaN

                                                             NRMSE_cnn_23_01
task     feature_name
task_1-1 equilibrium-beta_normal                                    0.380492
         equilibrium-beta_pol                                       0.401579
         equilibrium-beta_tor                                       0.396198
         equilibrium-bphi_rmag                                      0.440970
         equilibrium-bvac_rmag                                      0.336380
         equilibrium-elongation                                     0.344791
         equilibrium-elongation_axis                                0.413678
         equilibrium-magnetic_axis_r                                0.244135
         equilibrium-magnetic_axis_z                                0.404996
         equilibrium-minor_radius                                   0.274989
         equilibrium-q95                                            0.259409
         equilibrium-triangularity_lower                            0.320255
         equilibrium-triangularity_upper                            0.345832
         equilibrium-x_point_r                                      0.360117
         equilibrium-x_point_z                                      0.053393
task_1-2 equilibrium-lcfs_r                                         0.049816
         equilibrium-lcfs_z                                         0.038232
task_1-3 equilibrium-psi                                            0.120423
task_2-1 equilibrium-beta_normal                                    0.408769
         equilibrium-beta_pol                                       0.420999
         equilibrium-beta_tor                                       0.415768
         equilibrium-bphi_rmag                                      0.452619
         equilibrium-bvac_rmag                                      0.334951
         equilibrium-elongation                                     0.333697
         equilibrium-elongation_axis                                0.400383
         equilibrium-magnetic_axis_r                                0.231069
         equilibrium-magnetic_axis_z                                0.489550
         equilibrium-minor_radius                                   0.275708
         equilibrium-q95                                            0.255259
         equilibrium-triangularity_lower                            0.327705
         equilibrium-triangularity_upper                            0.380486
         equilibrium-x_point_r                                      0.463623
         equilibrium-x_point_z                                      0.063777
         pf_active-coil_current                                     0.301640
         pf_active-solenoid_current                                 0.173186
         summary-ip                                                 0.185266
task_2-2 equilibrium-lcfs_r                                         0.056861
         equilibrium-lcfs_z                                         0.049833
task_2-3 equilibrium-psi                                            0.096327
task_3-1 thomson_scattering-n_e                                          inf
         thomson_scattering-t_e                                     0.333697
task_3-2 soft_x_rays-horizontal_cam_lower                           0.350318
         soft_x_rays-horizontal_cam_upper                           0.599942
         spectrometer_visible-filter_spectrometer_dalpha...         0.609493
task_3-3 equilibrium-beta_normal                                    0.496527
         equilibrium-beta_pol                                       0.487106
         equilibrium-beta_tor                                       0.488765
         thomson_scattering-n_e                                          inf
         thomson_scattering-t_e                                     0.468213
task_4-1 soft_x_rays-horizontal_cam_lower                                NaN
         soft_x_rays-horizontal_cam_upper                                NaN
task_4-4 summary-ip                                                      NaN
task_4-5 magnetics-b_field_pol_probe_omv_voltage                         NaN
         magnetics-b_field_tor_probe_cc_field                            NaN

## Moving CNN files into the correct format for calling evaluation functions

In [ ]:
from pathlib import Path

dir_path = Path('/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01/')

for file in dir_path.iterdir():
    print(file)
    new_dir = file.parent/file.name.split('_evaluation')[0]
    new_dir.mkdir()
    file.rename(new_dir/'windows_metrics.csv')

In [1]:
from MAST_benchmark.evaluator import compute_task_metrics, compute_all_metrics
import pandas as pd

In [7]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_4-1 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-4 was yet evaluated, the corresponding files were not found.
Warning: task task_4-5 was yet evaluated, the corresponding files were not found.

In [8]:
pd.set_option('display.width', 500)
print(df_signals)

        task                                       feature_name          RMSE           MSE           MAE     NRMSE      NMAE
0   task_1-1                            equilibrium-beta_normal  4.213282e-01  5.293153e-01  3.083535e-01  0.519897  0.380492
1   task_1-1                               equilibrium-beta_pol  9.978961e-02  2.667449e-02  7.079668e-02  0.566036  0.401579
2   task_1-1                               equilibrium-beta_tor  9.994155e-01  2.661610e+00  7.889075e-01  0.501917  0.396198
3   task_1-1                              equilibrium-bphi_rmag  2.751502e-02  1.617332e-03  2.187909e-02  0.554561  0.440970
4   task_1-1                              equilibrium-bvac_rmag  2.042257e-02  7.909617e-04  1.825846e-02  0.376250  0.336380
5   task_1-1                             equilibrium-elongation  6.739340e-02  6.596718e-03  5.658072e-02  0.410682  0.344791
6   task_1-1                        equilibrium-elongation_axis  7.536777e-02  9.463764e-03  6.291435e-02  0.495563  0.413678
7   task_1-1                        equilibrium-magnetic_axis_r  2.376732e-02  8.044637e-04  1.991114e-02  0.291417  0.244135
8   task_1-1                        equilibrium-magnetic_axis_z  1.046621e-02  2.458256e-04  8.374295e-03  0.506165  0.404996
9   task_1-1                           equilibrium-minor_radius  1.749019e-02  4.575908e-04  1.461739e-02  0.329033  0.274989
10  task_1-1                                    equilibrium-q95  8.668640e-01  1.070958e+00  6.992082e-01  0.321610  0.259409
11  task_1-1                    equilibrium-triangularity_lower  3.193537e-02  1.417320e-03  2.691892e-02  0.379936  0.320255
12  task_1-1                    equilibrium-triangularity_upper  3.013362e-02  1.304473e-03  2.532577e-02  0.411485  0.345832
13  task_1-1                              equilibrium-x_point_r  6.731983e-02  7.999213e-02  4.303807e-02  0.528581  0.337926
14  task_1-1                              equilibrium-x_point_z  8.374822e-02  7.388665e-02  5.801384e-02  0.072540  0.050250
0   task_1-2                                 equilibrium-lcfs_r  2.146051e-02  5.789734e-04  1.521926e-02  0.057205  0.040569
1   task_1-2                                 equilibrium-lcfs_z  2.695049e-02  8.807609e-04  2.006897e-02  0.041846  0.031161
0   task_1-3                                    equilibrium-psi  1.081056e-02  2.385234e-04  4.826388e-03  0.204539  0.091317
0   task_2-1                            equilibrium-beta_normal  4.041106e-01  3.650121e-01  3.088345e-01  0.498651  0.381085
1   task_2-1                               equilibrium-beta_pol  9.137102e-02  1.996009e-02  6.963059e-02  0.518283  0.394965
2   task_2-1                               equilibrium-beta_tor  9.734545e-01  1.970165e+00  7.724616e-01  0.488879  0.387938
3   task_2-1                              equilibrium-bphi_rmag  2.599441e-02  1.356374e-03  2.110728e-02  0.523914  0.425414
4   task_2-1                              equilibrium-bvac_rmag  1.947830e-02  7.089606e-04  1.728439e-02  0.358854  0.318435
5   task_2-1                             equilibrium-elongation  6.137721e-02  5.529220e-03  5.140759e-02  0.374020  0.313267
6   task_2-1                        equilibrium-elongation_axis  6.887451e-02  8.074943e-03  5.734260e-02  0.452868  0.377043
7   task_2-1                        equilibrium-magnetic_axis_r  2.119090e-02  6.294368e-04  1.781529e-02  0.259827  0.218438
8   task_2-1                        equilibrium-magnetic_axis_z  1.176519e-02  3.021638e-04  9.418362e-03  0.568986  0.455489
9   task_2-1                           equilibrium-minor_radius  1.652749e-02  3.949110e-04  1.390850e-02  0.310922  0.261652
10  task_2-1                                    equilibrium-q95  7.934883e-01  9.234687e-01  6.525616e-01  0.294388  0.242103
11  task_2-1                    equilibrium-triangularity_lower  3.070389e-02  1.364029e-03  2.590739e-02  0.365285  0.308221
12  task_2-1                    equilibrium-triangularity_upper  3.058995e-02  1.280006e-03  2.614567e-02  0.417717  0.357028
13  task_2-1                              equilibrium-x_point_r  7.825663e-02  1.169734e-01  4.965909e-02  0.614454  0.389913
14  task_2-1                              equilibrium-x_point_z  9.151698e-02  1.003991e-01  6.284569e-02  0.079269  0.054435
15  task_2-1                             pf_active-coil_current  1.621453e+03  4.005212e+06  1.127445e+03  0.320316  0.222725
16  task_2-1                         pf_active-solenoid_current  2.399108e+03  7.247490e+06  2.015968e+03  0.192536  0.161788
17  task_2-1                                         summary-ip  5.664411e+04  4.783243e+09  4.852855e+04  0.198037  0.169664
0   task_2-2                                 equilibrium-lcfs_r  2.328889e-02  6.375195e-04  1.665948e-02  0.062079  0.044408
1   task_2-2                                 equilibrium-lcfs_z  3.418533e-02  1.311135e-03  2.520117e-02  0.053080  0.039130
0   task_2-3                                    equilibrium-psi  7.708846e-03  8.644648e-05  3.592354e-03  0.145853  0.067968
0   task_3-1                             thomson_scattering-n_e           inf           inf  3.338483e+18       inf  0.265794
1   task_3-1                             thomson_scattering-t_e  1.063728e+02  1.233250e+04  7.187948e+01  0.354664  0.239658
0   task_3-2                   soft_x_rays-horizontal_cam_lower  6.658603e-03  1.067924e-04  3.493742e-03  0.433775  0.227600
1   task_3-2                   soft_x_rays-horizontal_cam_upper  7.437990e-03  1.188937e-04  3.859612e-03  0.706662  0.366691
2   task_3-2  spectrometer_visible-filter_spectrometer_dalph...  2.700000e-01  9.168154e-02  1.720698e-01  0.697365  0.444428
0   task_3-3                            equilibrium-beta_normal  5.331265e-01  7.622298e-01  4.023889e-01  0.657850  0.496527
1   task_3-3                               equilibrium-beta_pol  1.167702e-01  3.305439e-02  8.587466e-02  0.662355  0.487106
2   task_3-3                               equilibrium-beta_tor  1.234607e+00  3.897420e+00  9.732271e-01  0.620033  0.488765
3   task_3-3                             thomson_scattering-n_e           inf           inf  6.808321e+18       inf  0.542045
4   task_3-3                             thomson_scattering-t_e  1.490119e+02  2.446043e+04  1.174342e+02  0.496830  0.391544

In [9]:
print(df_groups)

       task           MSE     NRMSE      NMAE
0   group_1  9.675195e-02  0.223995  0.151693
0  task_1-1  2.976756e-01  0.417712  0.330125
1  task_1-2  7.298671e-04  0.049526  0.035865
2  task_1-3  2.385234e-04  0.204539  0.091317
0   group_2  8.499047e+07  0.191672  0.134658
0  task_2-1  2.663609e+08  0.379845  0.302200
1  task_2-2  9.743271e-04  0.057579  0.041769
2  task_2-3  8.644648e-05  0.145853  0.067968
0   group_3           inf       inf  0.353522
0  task_3-1           inf       inf  0.252726
1  task_3-2  3.063574e-02  0.612601  0.346240
2  task_3-3           inf       inf  0.481197

In [10]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/persistence'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_1-1 was yet evaluated, the corresponding files were not found.
Warning: task task_1-2 was yet evaluated, the corresponding files were not found.
Warning: task task_1-3 was yet evaluated, the corresponding files were not found.
Warning: task task_2-2 was yet evaluated, the corresponding files were not found.
Warning: task task_2-3 was yet evaluated, the corresponding files were not found.
Warning: task task_3-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.

In [11]:
print(df_signals)

       task                                       feature_name      RMSE       MAE         NRMSE          NMAE
0  task_2-1                             pf_active-coil_current  0.271530  0.092387  5.364052e-05  1.825095e-05
1  task_2-1                         pf_active-solenoid_current  0.176495  0.131879  1.416424e-05  1.058370e-05
2  task_2-1                                         summary-ip  0.338200  0.132160  1.182406e-06  4.620541e-07
0  task_3-1                             thomson_scattering-n_e  0.447473  0.285560  3.562563e-20  2.273490e-20
1  task_3-1                             thomson_scattering-t_e  0.489810  0.277151  1.633105e-03  9.240651e-04
0  task_3-2                   soft_x_rays-horizontal_cam_lower  0.404062  0.158488  2.632268e+01  1.032472e+01
1  task_3-2                   soft_x_rays-horizontal_cam_upper  0.753806  0.294666  7.161695e+01  2.799533e+01
2  task_3-2  spectrometer_visible-filter_spectrometer_dalph...  0.759152  0.338289  1.960764e+00  8.737438e-01
0  task_4-1                   soft_x_rays-horizontal_cam_lower  0.531934  0.234866  3.465285e+01  1.530037e+01
1  task_4-1                   soft_x_rays-horizontal_cam_upper  0.916349  0.450026  8.705969e+01  4.275572e+01
0  task_4-4                                         summary-ip  0.760081  0.460417  2.657374e-06  1.609697e-06
0  task_4-5            magnetics-b_field_pol_probe_omv_voltage  1.721265  0.895360  1.309427e+01  6.811324e+00
1  task_4-5               magnetics-b_field_tor_probe_cc_field  1.766652  0.622617  1.095489e+05  3.860804e+04

In [5]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/mean'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_1-1 was yet evaluated, the corresponding files were not found.
Warning: task task_1-2 was yet evaluated, the corresponding files were not found.
Warning: task task_1-3 was yet evaluated, the corresponding files were not found.
Warning: task task_3-1 was yet evaluated, the corresponding files were not found.
Warning: task task_3-2 was yet evaluated, the corresponding files were not found.
Warning: task task_3-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-1 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-4 was yet evaluated, the corresponding files were not found.
Warning: task task_4-5 was yet evaluated, the corresponding files were not found.

In [6]:
pd.set_option('display.width', 500)
print(df_signals)

        task                     feature_name           RMSE            MAE       NRMSE        NMAE
0   task_2-1          equilibrium-beta_normal       1.496987       1.300398    1.847203    1.604623
1   task_2-1             equilibrium-beta_pol       1.144067       0.876273    6.489477    4.970478
2   task_2-1             equilibrium-beta_tor       2.393552       2.206606    1.202067    1.108181
3   task_2-1            equilibrium-bphi_rmag       2.147387       1.853695   43.280278   37.360955
4   task_2-1            equilibrium-bvac_rmag       1.795784       1.479078   33.084181   27.249425
5   task_2-1           equilibrium-elongation       1.217190       1.029778    7.417308    6.275258
6   task_2-1      equilibrium-elongation_axis       1.242066       1.058367    8.166915    6.959045
7   task_2-1      equilibrium-magnetic_axis_r       1.006280       0.822436   12.338239   10.084085
8   task_2-1      equilibrium-magnetic_axis_z       2.269789       2.091282  109.771106  101.138198
9   task_2-1         equilibrium-minor_radius       0.993604       0.782985   18.692094   14.729835
10  task_2-1                  equilibrium-q95       2.926941       2.790272    1.085908    1.035203
11  task_2-1  equilibrium-triangularity_lower       1.072737       0.936098   12.762399   11.136794
12  task_2-1  equilibrium-triangularity_upper       1.268828       1.156520   17.326297   15.792702
13  task_2-1            equilibrium-x_point_r       1.403065       1.028086   11.016569    8.072310
14  task_2-1            equilibrium-x_point_z       1.776301       1.394020    1.538579    1.207459
15  task_2-1           pf_active-coil_current    5062.045255    5062.045149    1.000001    1.000001
16  task_2-1       pf_active-solenoid_current   12460.582004   12460.581962    1.000001    1.000001
17  task_2-1                       summary-ip  286027.179821  286027.179819    1.000000    1.000000
0   task_2-2               equilibrium-lcfs_r       1.070134       0.928136    2.852568    2.474054
1   task_2-2               equilibrium-lcfs_z       1.205319       1.000889    1.871500    1.554081
0   task_2-3                  equilibrium-psi       0.967186       0.744839   18.299424   14.092556