### Joining results from several models

In [1]:
from pathlib import Path
import pandas as pd

In [ ]:
base_model = ('persistence', '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/persistence/')
models_to_join = {
    'cnn_23_01' : '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01/'
}

In [5]:
def join_results(metrics_file, metric_columns, index_column):
    def rename_cols(cols, suffix):
        return {col : col+'_'+suffix for col in cols}

    df_groups_joined  = pd.read_csv(
        Path(base_model[1])/metrics_file, index_col=index_column)\
        [metric_columns]\
        .rename(columns=rename_cols(metric_columns, base_model[0]))

    for model in models_to_join:
        df_groups = pd.read_csv(
            Path(models_to_join[model])/metrics_file, index_col=index_column)\
            [metric_columns]\
            .rename(columns=rename_cols(metric_columns, model))

        df_groups_joined = df_groups_joined.join(
            df_groups,
            how='outer'
        )
    return df_groups_joined

df_groups_joined = join_results(metrics_file='groups_metrics.csv', metric_columns=['NRMSE'], index_column='task')
df_groups_joined

          NRMSE_persistence  NRMSE_cnn_23_01
task
group_1                 NaN         0.165317
group_2            0.000015         0.156939
group_3           13.275136              inf
group_4          341.175353              NaN
task_1-1                NaN         0.331814
task_1-2                NaN         0.044024
task_1-3                NaN         0.120423
task_2-1           0.000015         0.328581
task_2-2                NaN         0.053347
task_2-3                NaN         0.096327
task_3-1           0.000738              inf
task_3-2          24.078520         0.519917
task_3-3                NaN              inf
task_4-1          42.884167              NaN
task_4-4           0.000002              NaN
task_4-5       28122.252853              NaN

In [7]:
df_signals_joined = join_results(metrics_file='signals_metrics.csv', metric_columns=['RMSE','NRMSE'], index_column=['task', 'feature_name'])
df_signals_joined

                                                             RMSE_persistence  \
task     feature_name
task_1-1 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         equilibrium-bphi_rmag                                            NaN
         equilibrium-bvac_rmag                                            NaN
         equilibrium-elongation                                           NaN
         equilibrium-elongation_axis                                      NaN
         equilibrium-magnetic_axis_r                                      NaN
         equilibrium-magnetic_axis_z                                      NaN
         equilibrium-minor_radius                                         NaN
         equilibrium-q95                                                  NaN
         equilibrium-triangularity_lower                                  NaN
         equilibrium-triangularity_upper                                  NaN
         equilibrium-x_point_r                                            NaN
         equilibrium-x_point_z                                            NaN
task_1-2 equilibrium-lcfs_r                                               NaN
         equilibrium-lcfs_z                                               NaN
task_1-3 equilibrium-psi                                                  NaN
task_2-1 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         equilibrium-bphi_rmag                                            NaN
         equilibrium-bvac_rmag                                            NaN
         equilibrium-elongation                                           NaN
         equilibrium-elongation_axis                                      NaN
         equilibrium-magnetic_axis_r                                      NaN
         equilibrium-magnetic_axis_z                                      NaN
         equilibrium-minor_radius                                         NaN
         equilibrium-q95                                                  NaN
         equilibrium-triangularity_lower                                  NaN
         equilibrium-triangularity_upper                                  NaN
         equilibrium-x_point_r                                            NaN
         equilibrium-x_point_z                                            NaN
         pf_active-coil_current                                      0.160581
         pf_active-solenoid_current                                  0.152229
         summary-ip                                                  0.159397
task_2-2 equilibrium-lcfs_r                                               NaN
         equilibrium-lcfs_z                                               NaN
task_2-3 equilibrium-psi                                                  NaN
task_3-1 thomson_scattering-n_e                                      0.423540
         thomson_scattering-t_e                                      0.442482
task_3-2 soft_x_rays-horizontal_cam_lower                            0.281268
         soft_x_rays-horizontal_cam_upper                            0.562667
         spectrometer_visible-filter_spectrometer_dalpha...          0.502936
task_3-3 equilibrium-beta_normal                                          NaN
         equilibrium-beta_pol                                             NaN
         equilibrium-beta_tor                                             NaN
         thomson_scattering-n_e                                           NaN
         thomson_scattering-t_e                                           NaN
task_4-1 soft_x_rays-horizontal_cam_lower                            0.441886
         soft_x_rays-horizontal_cam_upper                            0.793485
task_4-4 summary-ip                                                  0.575937
task_4-5 magnetics-b_field_pol_probe_omv_voltage                     1.365683
         magnetics-b_field_tor_probe_cc_field                        1.256059

                                                             NRMSE_persistence  \
task     feature_name
task_1-1 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         equilibrium-bphi_rmag                                             NaN
         equilibrium-bvac_rmag                                             NaN
         equilibrium-elongation                                            NaN
         equilibrium-elongation_axis                                       NaN
         equilibrium-magnetic_axis_r                                       NaN
         equilibrium-magnetic_axis_z                                       NaN
         equilibrium-minor_radius                                          NaN
         equilibrium-q95                                                   NaN
         equilibrium-triangularity_lower                                   NaN
         equilibrium-triangularity_upper                                   NaN
         equilibrium-x_point_r                                             NaN
         equilibrium-x_point_z                                             NaN
task_1-2 equilibrium-lcfs_r                                                NaN
         equilibrium-lcfs_z                                                NaN
task_1-3 equilibrium-psi                                                   NaN
task_2-1 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         equilibrium-bphi_rmag                                             NaN
         equilibrium-bvac_rmag                                             NaN
         equilibrium-elongation                                            NaN
         equilibrium-elongation_axis                                       NaN
         equilibrium-magnetic_axis_r                                       NaN
         equilibrium-magnetic_axis_z                                       NaN
         equilibrium-minor_radius                                          NaN
         equilibrium-q95                                                   NaN
         equilibrium-triangularity_lower                                   NaN
         equilibrium-triangularity_upper                                   NaN
         equilibrium-x_point_r                                             NaN
         equilibrium-x_point_z                                             NaN
         pf_active-coil_current                                   3.172252e-05
         pf_active-solenoid_current                               1.221689e-05
         summary-ip                                               5.572782e-07
task_2-2 equilibrium-lcfs_r                                                NaN
         equilibrium-lcfs_z                                                NaN
task_2-3 equilibrium-psi                                                   NaN
task_3-1 thomson_scattering-n_e                                   3.372019e-20
         thomson_scattering-t_e                                   1.475307e-03
task_3-2 soft_x_rays-horizontal_cam_lower                         1.832320e+01
         soft_x_rays-horizontal_cam_upper                         5.345743e+01
         spectrometer_visible-filter_spectrometer_dalpha...       1.298999e+00
task_3-3 equilibrium-beta_normal                                           NaN
         equilibrium-beta_pol                                              NaN
         equilibrium-beta_tor                                              NaN
         thomson_scattering-n_e                                            NaN
         thomson_scattering-t_e                                            NaN
task_4-1 soft_x_rays-horizontal_cam_lower                         2.878671e+01
         soft_x_rays-horizontal_cam_upper                         7.538676e+01
task_4-4 summary-ip                                               2.013572e-06
task_4-5 magnetics-b_field_pol_probe_omv_voltage                  1.038924e+01
         magnetics-b_field_tor_probe_cc_field                     7.788733e+04

                                                             RMSE_cnn_23_01  \
task     feature_name
task_1-1 equilibrium-beta_normal                               3.083535e-01
         equilibrium-beta_pol                                  7.079668e-02
         equilibrium-beta_tor                                  7.889075e-01
         equilibrium-bphi_rmag                                 2.187909e-02
         equilibrium-bvac_rmag                                 1.825846e-02
         equilibrium-elongation                                5.658072e-02
         equilibrium-elongation_axis                           6.291435e-02
         equilibrium-magnetic_axis_r                           1.991114e-02
         equilibrium-magnetic_axis_z                           8.374295e-03
         equilibrium-minor_radius                              1.461739e-02
         equilibrium-q95                                       6.992082e-01
         equilibrium-triangularity_lower                       2.691892e-02
         equilibrium-triangularity_upper                       2.532577e-02
         equilibrium-x_point_r                                 4.586435e-02
         equilibrium-x_point_z                                 6.164280e-02
task_1-2 equilibrium-lcfs_r                                    1.868824e-02
         equilibrium-lcfs_z                                    2.462266e-02
task_1-3 equilibrium-psi                                       6.364746e-03
task_2-1 equilibrium-beta_normal                               3.312698e-01
         equilibrium-beta_pol                                  7.422029e-02
         equilibrium-beta_tor                                  8.278749e-01
         equilibrium-bphi_rmag                                 2.245707e-02
         equilibrium-bvac_rmag                                 1.818091e-02
         equilibrium-elongation                                5.476007e-02
         equilibrium-elongation_axis                           6.089234e-02
         equilibrium-magnetic_axis_r                           1.884552e-02
         equilibrium-magnetic_axis_z                           1.012266e-02
         equilibrium-minor_radius                              1.465561e-02
         equilibrium-q95                                       6.880221e-01
         equilibrium-triangularity_lower                       2.754508e-02
         equilibrium-triangularity_upper                       2.786351e-02
         equilibrium-x_point_r                                 5.904679e-02
         equilibrium-x_point_z                                 7.363112e-02
         pf_active-coil_current                                1.526914e+03
         pf_active-solenoid_current                            2.158003e+03
         summary-ip                                            5.299098e+04
task_2-2 equilibrium-lcfs_r                                    2.133111e-02
         equilibrium-lcfs_z                                    3.209471e-02
task_2-3 equilibrium-psi                                       5.091208e-03
task_3-1 thomson_scattering-n_e                                         inf
         thomson_scattering-t_e                                1.000844e+02
task_3-2 soft_x_rays-horizontal_cam_lower                      5.377505e-03
         soft_x_rays-horizontal_cam_upper                      6.314699e-03
         spectrometer_visible-filter_spectrometer_dalpha...    2.359782e-01
task_3-3 equilibrium-beta_normal                               4.023889e-01
         equilibrium-beta_pol                                  8.587466e-02
         equilibrium-beta_tor                                  9.732271e-01
         thomson_scattering-n_e                                         inf
         thomson_scattering-t_e                                1.404292e+02
task_4-1 soft_x_rays-horizontal_cam_lower                               NaN
         soft_x_rays-horizontal_cam_upper                               NaN
task_4-4 summary-ip                                                     NaN
task_4-5 magnetics-b_field_pol_probe_omv_voltage                        NaN
         magnetics-b_field_tor_probe_cc_field                           NaN

                                                             NRMSE_cnn_23_01
task     feature_name
task_1-1 equilibrium-beta_normal                                    0.380492
         equilibrium-beta_pol                                       0.401579
         equilibrium-beta_tor                                       0.396198
         equilibrium-bphi_rmag                                      0.440970
         equilibrium-bvac_rmag                                      0.336380
         equilibrium-elongation                                     0.344791
         equilibrium-elongation_axis                                0.413678
         equilibrium-magnetic_axis_r                                0.244135
         equilibrium-magnetic_axis_z                                0.404996
         equilibrium-minor_radius                                   0.274989
         equilibrium-q95                                            0.259409
         equilibrium-triangularity_lower                            0.320255
         equilibrium-triangularity_upper                            0.345832
         equilibrium-x_point_r                                      0.360117
         equilibrium-x_point_z                                      0.053393
task_1-2 equilibrium-lcfs_r                                         0.049816
         equilibrium-lcfs_z                                         0.038232
task_1-3 equilibrium-psi                                            0.120423
task_2-1 equilibrium-beta_normal                                    0.408769
         equilibrium-beta_pol                                       0.420999
         equilibrium-beta_tor                                       0.415768
         equilibrium-bphi_rmag                                      0.452619
         equilibrium-bvac_rmag                                      0.334951
         equilibrium-elongation                                     0.333697
         equilibrium-elongation_axis                                0.400383
         equilibrium-magnetic_axis_r                                0.231069
         equilibrium-magnetic_axis_z                                0.489550
         equilibrium-minor_radius                                   0.275708
         equilibrium-q95                                            0.255259
         equilibrium-triangularity_lower                            0.327705
         equilibrium-triangularity_upper                            0.380486
         equilibrium-x_point_r                                      0.463623
         equilibrium-x_point_z                                      0.063777
         pf_active-coil_current                                     0.301640
         pf_active-solenoid_current                                 0.173186
         summary-ip                                                 0.185266
task_2-2 equilibrium-lcfs_r                                         0.056861
         equilibrium-lcfs_z                                         0.049833
task_2-3 equilibrium-psi                                            0.096327
task_3-1 thomson_scattering-n_e                                          inf
         thomson_scattering-t_e                                     0.333697
task_3-2 soft_x_rays-horizontal_cam_lower                           0.350318
         soft_x_rays-horizontal_cam_upper                           0.599942
         spectrometer_visible-filter_spectrometer_dalpha...         0.609493
task_3-3 equilibrium-beta_normal                                    0.496527
         equilibrium-beta_pol                                       0.487106
         equilibrium-beta_tor                                       0.488765
         thomson_scattering-n_e                                          inf
         thomson_scattering-t_e                                     0.468213
task_4-1 soft_x_rays-horizontal_cam_lower                                NaN
         soft_x_rays-horizontal_cam_upper                                NaN
task_4-4 summary-ip                                                      NaN
task_4-5 magnetics-b_field_pol_probe_omv_voltage                         NaN
         magnetics-b_field_tor_probe_cc_field                            NaN

## Moving CNN files into the correct format for calling evaluation functions

In [ ]:
from pathlib import Path

dir_path = Path('/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01/')

for file in dir_path.iterdir():
    print(file)
    new_dir = file.parent/file.name.split('_evaluation')[0]
    new_dir.mkdir()
    file.rename(new_dir/'windows_metrics.csv')

In [1]:
from MAST_benchmark.evaluator import compute_task_metrics, compute_all_metrics
import pandas as pd

In [2]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/cnn_23_01'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_4-1 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-4 was yet evaluated, the corresponding files were not found.
Warning: task task_4-5 was yet evaluated, the corresponding files were not found.

In [3]:
pd.set_option('display.width', 500)
print(df_signals)

        task                                       feature_name          RMSE           MSE           MAE     NRMSE      NMAE
0   task_1-1                            equilibrium-beta_normal  3.083535e-01  5.293153e-01  3.083535e-01  0.380492  0.380492
1   task_1-1                               equilibrium-beta_pol  7.079668e-02  2.667449e-02  7.079668e-02  0.401579  0.401579
2   task_1-1                               equilibrium-beta_tor  7.889075e-01  2.661610e+00  7.889075e-01  0.396198  0.396198
3   task_1-1                              equilibrium-bphi_rmag  2.187909e-02  1.617332e-03  2.187909e-02  0.440970  0.440970
4   task_1-1                              equilibrium-bvac_rmag  1.825846e-02  7.909617e-04  1.825846e-02  0.336380  0.336380
5   task_1-1                             equilibrium-elongation  5.658072e-02  6.596718e-03  5.658072e-02  0.344791  0.344791
6   task_1-1                        equilibrium-elongation_axis  6.291435e-02  9.463764e-03  6.291435e-02  0.413678  0.413678
7   task_1-1                        equilibrium-magnetic_axis_r  1.991114e-02  8.044637e-04  1.991114e-02  0.244135  0.244135
8   task_1-1                        equilibrium-magnetic_axis_z  8.374295e-03  2.458256e-04  8.374295e-03  0.404996  0.404996
9   task_1-1                           equilibrium-minor_radius  1.461739e-02  4.575908e-04  1.461739e-02  0.274989  0.274989
10  task_1-1                                    equilibrium-q95  6.992082e-01  1.070958e+00  6.992082e-01  0.259409  0.259409
11  task_1-1                    equilibrium-triangularity_lower  2.691892e-02  1.417320e-03  2.691892e-02  0.320255  0.320255
12  task_1-1                    equilibrium-triangularity_upper  2.532577e-02  1.304473e-03  2.532577e-02  0.345832  0.345832
13  task_1-1                              equilibrium-x_point_r  4.586435e-02  7.999213e-02  4.303807e-02  0.360117  0.337926
14  task_1-1                              equilibrium-x_point_z  6.164280e-02  7.388665e-02  5.801384e-02  0.053393  0.050250
0   task_1-2                                 equilibrium-lcfs_r  1.868824e-02  5.789734e-04  1.521926e-02  0.049816  0.040569
1   task_1-2                                 equilibrium-lcfs_z  2.462266e-02  8.807609e-04  2.006897e-02  0.038232  0.031161
0   task_1-3                                    equilibrium-psi  6.364746e-03  2.385234e-04  4.826388e-03  0.120423  0.091317
0   task_2-1                            equilibrium-beta_normal  3.312698e-01  3.650121e-01  3.088345e-01  0.408769  0.381085
1   task_2-1                               equilibrium-beta_pol  7.422029e-02  1.996009e-02  6.963059e-02  0.420999  0.394965
2   task_2-1                               equilibrium-beta_tor  8.278749e-01  1.970165e+00  7.724616e-01  0.415768  0.387938
3   task_2-1                              equilibrium-bphi_rmag  2.245707e-02  1.356374e-03  2.110728e-02  0.452619  0.425414
4   task_2-1                              equilibrium-bvac_rmag  1.818091e-02  7.089606e-04  1.728439e-02  0.334951  0.318435
5   task_2-1                             equilibrium-elongation  5.476007e-02  5.529220e-03  5.140759e-02  0.333697  0.313267
6   task_2-1                        equilibrium-elongation_axis  6.089234e-02  8.074943e-03  5.734260e-02  0.400383  0.377043
7   task_2-1                        equilibrium-magnetic_axis_r  1.884552e-02  6.294368e-04  1.781529e-02  0.231069  0.218438
8   task_2-1                        equilibrium-magnetic_axis_z  1.012266e-02  3.021638e-04  9.418362e-03  0.489550  0.455489
9   task_2-1                           equilibrium-minor_radius  1.465561e-02  3.949110e-04  1.390850e-02  0.275708  0.261652
10  task_2-1                                    equilibrium-q95  6.880221e-01  9.234687e-01  6.525616e-01  0.255259  0.242103
11  task_2-1                    equilibrium-triangularity_lower  2.754508e-02  1.364029e-03  2.590739e-02  0.327705  0.308221
12  task_2-1                    equilibrium-triangularity_upper  2.786351e-02  1.280006e-03  2.614567e-02  0.380486  0.357028
13  task_2-1                              equilibrium-x_point_r  5.904679e-02  1.169734e-01  4.965909e-02  0.463623  0.389913
14  task_2-1                              equilibrium-x_point_z  7.363112e-02  1.003991e-01  6.284569e-02  0.063777  0.054435
15  task_2-1                             pf_active-coil_current  1.526914e+03  4.005212e+06  1.127445e+03  0.301640  0.222725
16  task_2-1                         pf_active-solenoid_current  2.158003e+03  7.247490e+06  2.015968e+03  0.173186  0.161788
17  task_2-1                                         summary-ip  5.299098e+04  4.783243e+09  4.852855e+04  0.185266  0.169664
0   task_2-2                                 equilibrium-lcfs_r  2.133111e-02  6.375195e-04  1.665948e-02  0.056861  0.044408
1   task_2-2                                 equilibrium-lcfs_z  3.209471e-02  1.311135e-03  2.520117e-02  0.049833  0.039130
0   task_2-3                                    equilibrium-psi  5.091208e-03  8.644648e-05  3.592354e-03  0.096327  0.067968
0   task_3-1                             thomson_scattering-n_e           inf           inf  3.338483e+18       inf  0.265794
1   task_3-1                             thomson_scattering-t_e  1.000844e+02  1.233250e+04  7.187948e+01  0.333697  0.239658
0   task_3-2                   soft_x_rays-horizontal_cam_lower  5.377505e-03  1.067924e-04  3.493742e-03  0.350318  0.227600
1   task_3-2                   soft_x_rays-horizontal_cam_upper  6.314699e-03  1.188937e-04  3.859612e-03  0.599942  0.366691
2   task_3-2  spectrometer_visible-filter_spectrometer_dalph...  2.359782e-01  9.168154e-02  1.720698e-01  0.609493  0.444428
0   task_3-3                            equilibrium-beta_normal  4.023889e-01  7.622298e-01  4.023889e-01  0.496527  0.496527
1   task_3-3                               equilibrium-beta_pol  8.587466e-02  3.305439e-02  8.587466e-02  0.487106  0.487106
2   task_3-3                               equilibrium-beta_tor  9.732271e-01  3.897420e+00  9.732271e-01  0.488765  0.488765
3   task_3-3                             thomson_scattering-n_e           inf           inf  6.808321e+18       inf  0.542045
4   task_3-3                             thomson_scattering-t_e  1.404292e+02  2.446043e+04  1.174342e+02  0.468213  0.391544

In [4]:
print(df_groups)

       task           MSE     NRMSE      NMAE
0   group_1  9.675195e-02  0.165317  0.151693
0  task_1-1  2.976756e-01  0.331814  0.330125
1  task_1-2  7.298671e-04  0.044024  0.035865
2  task_1-3  2.385234e-04  0.120423  0.091317
0   group_2  8.499047e+07  0.156939  0.134658
0  task_2-1  2.663609e+08  0.328581  0.302200
1  task_2-2  9.743271e-04  0.053347  0.041769
2  task_2-3  8.644648e-05  0.096327  0.067968
0   group_3           inf       inf  0.353522
0  task_3-1           inf       inf  0.252726
1  task_3-2  3.063574e-02  0.519917  0.346240
2  task_3-3           inf       inf  0.481197

In [5]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/persistence'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_1-1 was yet evaluated, the corresponding files were not found.
Warning: task task_1-2 was yet evaluated, the corresponding files were not found.
Warning: task task_1-3 was yet evaluated, the corresponding files were not found.
Warning: task task_2-2 was yet evaluated, the corresponding files were not found.
Warning: task task_2-3 was yet evaluated, the corresponding files were not found.
Warning: task task_3-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.

In [6]:
print(df_signals)

       task                                       feature_name      RMSE       MAE         NRMSE          NMAE
0  task_2-1                             pf_active-coil_current  0.160581  0.092387  3.172252e-05  1.825095e-05
1  task_2-1                         pf_active-solenoid_current  0.152229  0.131879  1.221689e-05  1.058370e-05
2  task_2-1                                         summary-ip  0.159397  0.132160  5.572782e-07  4.620541e-07
0  task_3-1                             thomson_scattering-n_e  0.423540  0.285560  3.372019e-20  2.273490e-20
1  task_3-1                             thomson_scattering-t_e  0.442482  0.277151  1.475307e-03  9.240651e-04
0  task_3-2                   soft_x_rays-horizontal_cam_lower  0.281268  0.158488  1.832320e+01  1.032472e+01
1  task_3-2                   soft_x_rays-horizontal_cam_upper  0.562667  0.294666  5.345743e+01  2.799533e+01
2  task_3-2  spectrometer_visible-filter_spectrometer_dalph...  0.502936  0.338289  1.298999e+00  8.737438e-01
0  task_4-1                   soft_x_rays-horizontal_cam_lower  0.441886  0.234866  2.878671e+01  1.530037e+01
1  task_4-1                   soft_x_rays-horizontal_cam_upper  0.793485  0.450026  7.538676e+01  4.275572e+01
0  task_4-4                                         summary-ip  0.575937  0.460417  2.013572e-06  1.609697e-06
0  task_4-5            magnetics-b_field_pol_probe_omv_voltage  1.365683  0.895360  1.038924e+01  6.811324e+00
1  task_4-5               magnetics-b_field_tor_probe_cc_field  1.256059  0.622617  7.788733e+04  3.860804e+04

In [7]:
model_dir = '/home/ir-zaya1/fusion/fairmast-data-preprocessing/output/mean'
df_signals, df_groups = compute_all_metrics(model_dir)

Warning: task task_1-1 was yet evaluated, the corresponding files were not found.
Warning: task task_1-2 was yet evaluated, the corresponding files were not found.
Warning: task task_1-3 was yet evaluated, the corresponding files were not found.
Warning: task task_2-2 was yet evaluated, the corresponding files were not found.
Warning: task task_2-3 was yet evaluated, the corresponding files were not found.
Warning: task task_3-1 was yet evaluated, the corresponding files were not found.
Warning: task task_3-2 was yet evaluated, the corresponding files were not found.
Warning: task task_3-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-1 was yet evaluated, the corresponding files were not found.
Warning: task task_4-2 was yet evaluated, the corresponding files were not found.
Warning: task task_4-3 was yet evaluated, the corresponding files were not found.
Warning: task task_4-4 was yet evaluated, the corresponding files were not found.
Warning: task task_4-5 was yet evaluated, the corresponding files were not found.

In [8]:
print(df_signals)

        task                     feature_name           RMSE            MAE       NRMSE        NMAE
0   task_2-1          equilibrium-beta_normal       1.321869       1.300398    1.631117    1.604623
1   task_2-1             equilibrium-beta_pol       0.907340       0.876273    5.146699    4.970478
2   task_2-1             equilibrium-beta_tor       2.220459       2.206606    1.115138    1.108181
3   task_2-1            equilibrium-bphi_rmag       1.881220       1.853695   37.915716   37.360955
4   task_2-1            equilibrium-bvac_rmag       1.491825       1.479078   27.484266   27.249425
5   task_2-1           equilibrium-elongation       1.056062       1.029778    6.435423    6.275258
6   task_2-1      equilibrium-elongation_axis       1.087703       1.058367    7.151936    6.959045
7   task_2-1      equilibrium-magnetic_axis_r       0.836934       0.822436   10.261852   10.084085
8   task_2-1      equilibrium-magnetic_axis_z       2.112060       2.091282  102.143066  101.138198
9   task_2-1         equilibrium-minor_radius       0.803575       0.782985   15.117195   14.729835
10  task_2-1                  equilibrium-q95       2.801463       2.790272    1.039355    1.035203
11  task_2-1  equilibrium-triangularity_lower       0.955892       0.936098   11.372288   11.136794
12  task_2-1  equilibrium-triangularity_upper       1.180818       1.156520   16.124491   15.792702
13  task_2-1            equilibrium-x_point_r       1.113785       1.028086    8.745206    8.072310
14  task_2-1            equilibrium-x_point_z       1.755747       1.394020    1.520776    1.207459
15  task_2-1           pf_active-coil_current    5062.045239    5062.045149    1.000001    1.000001
16  task_2-1       pf_active-solenoid_current   12460.581962   12460.581962    1.000001    1.000001
17  task_2-1                       summary-ip  286027.179819  286027.179819    1.000000    1.000000